# Based on https://github.com/Koihik/LuaFormatter/blob/master/.travis.yml
language: cpp

matrix:
  include:
    # linux gcc
    - os: linux
      env:
        - COMPILER='g++-9'

    # os X
    - os: osx
      osx_image: xcode11
      compiler: clang
      env:
        - COMPILER='clang++'
        - MYLDFLAGS='-L/usr/local/opt/llvm/lib'
        - MYCXXFLAGS='-I/usr/local/opt/llvm/include'
        - MYPATH='/usr/local/opt/llvm/bin'

addons:
  homebrew:
    packages:
      - llvm
    update: true
  apt:
    sources:
      - sourceline: "ppa:ubuntu-toolchain-r/test"
    packages:
      - g++-9
    update: true

before_install:
  - export PATH="${MYPATH}:$PATH"
  - export CXX=${COMPILER}
  - export LDFLAGS=${MYLDFLAGS}
  - export CXXFLAGS=${MYCXXFLAGS}
  - git clone --depth 1 https://github.com/Koihik/LuaFormatter.git
  - cd LuaFormatter
  - git submodule update --init

install:
  - cd LuaFormatter
  - cmake -E env LDFLAGS="$LDFLAGS" CXXFLAGS="$CXXFLAGS" cmake . -BRelease -DCMAKE_BUILD_TYPE=Release
  - cmake -E env LDFLAGS="$LDFLAGS" CXXFLAGS="$CXXFLAGS" cmake . -BDebug -DCMAKE_BUILD_TYPE=Debug

script:
  - cd LuaFormatter
  - cd Debug
  - make -j 2
  - CTEST_OUTPUT_ON_FAILURE=1 ctest -j 2
  - cd ../Release
  - make -j 2
  - CTEST_OUTPUT_ON_FAILURE=1 ctest -j 2
