# Based on https://github.com/Koihik/LuaFormatter/blob/master/.travis.yml
language: cpp

matrix:
  include:
    # linux gcc
    - os: linux
      env:
        - COMPILER='g++-9'

    # os X
    - os: osx
      osx_image: xcode11
      compiler: clang
      env:
        - COMPILER='clang++'
        - MYLDFLAGS='-L/usr/local/opt/llvm/lib'
        - MYCXXFLAGS='-I/usr/local/opt/llvm/include'
        - MYPATH='/usr/local/opt/llvm/bin'

addons:
  homebrew:
    packages:
      - llvm
    update: true
  apt:
    sources:
      - sourceline: "ppa:ubuntu-toolchain-r/test"
    packages:
      - g++-9
    update: true

before_install:
  - export PATH="${MYPATH}:$PATH"
  - export CXX=${COMPILER}
  - export LDFLAGS=${MYLDFLAGS}
  - export CXXFLAGS=${MYCXXFLAGS}
  - git clone --depth 1 https://github.com/Koihik/LuaFormatter.git
  - cd LuaFormatter
  - export LF_GIT_TAG=$(git tag --sort=committerdate | tail -1)
  - export LF_GIT_HASH=$(git rev-parse --short HEAD)
  - git submodule update --init

install:
  - cmake -E env LDFLAGS="$LDFLAGS" CXXFLAGS="$CXXFLAGS" cmake . -BRelease -DCMAKE_BUILD_TYPE=Release
  - cmake -E env LDFLAGS="$LDFLAGS" CXXFLAGS="$CXXFLAGS" cmake . -BDebug -DCMAKE_BUILD_TYPE=Debug

script:
  - cd Debug
  - make -j 2
  - CTEST_OUTPUT_ON_FAILURE=1 ctest -j 2
  - cd ../Release
  - make -j 2
  - CTEST_OUTPUT_ON_FAILURE=1 ctest -j 2

after_success:
  - git config --global user.email "${GITHUB_EMAIL}"
  - git config --global user.name "${GITHUB_USERNAME}"
  - git clone https://${GITHUB_TOKEN}@github.com/indiesoftby/defold-editor-script-lua-format.git ${TRAVIS_BUILD_DIR}/main-repo
  - cd ${TRAVIS_BUILD_DIR}/main-repo
  - if [[ $TRAVIS_OS_NAME == "linux" && $COMPILER == "g++-9" ]]; then
      cp ${TRAVIS_BUILD_DIR}/LuaFormatter/Release/lua-format editor-script-lua-format/bin/linux/lua-format;
      chmod +x editor-script-lua-format/bin/linux/lua-format;
      git add editor-script-lua-format/bin/linux/lua-format;
      git commit -m "Update Linux build (version $LF_GIT_TAG-$LF_GIT_HASH)";
      git push;
    fi
  - if [[ $TRAVIS_OS_NAME == "osx" && $TRAVIS_OSX_IMAGE == "xcode11" ]]; then
      cp ${TRAVIS_BUILD_DIR}/LuaFormatter/Release/lua-format editor-script-lua-format/bin/darwin/lua-format;
      chmod +x editor-script-lua-format/bin/darwin/lua-format;
      git add editor-script-lua-format/bin/darwin/lua-format;
      git commit -m "Update macOS build (version $LF_GIT_TAG-$LF_GIT_HASH)";
      git push;
    fi
